apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kotlin-app
spec:
  selector:
    matchLabels:
      app: spring-kotlin-app
      version: 0.2.0
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-kotlin-app
        version: 0.2.0
    spec:
      containers:
        - name: spring-kotlin-app
          image: adrmarciao/account-hexa-service-kotlin:0.2.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: account-hexa-service-config
          ports:
            - containerPort: 8080