apiVersion: v1
kind: ConfigMap
metadata:
  name: account-hexa-service-config
data:
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "db"
  PGDATA: /var/lib/postgresql/data/pgdata